# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Wigit' do
pod 'Backendless'
end

target 'WigitTests' do

end

target 'WigitUITests' do

end

